

{{- if .Values.rbac.enabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "jira-service-desk-operator.fullname" . }}-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - jiraservicedesk.stakater.com
  resources:
  - customers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jiraservicedesk.stakater.com
  resources:
  - customers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - jiraservicedesk.stakater.com
  resources:
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jiraservicedesk.stakater.com
  resources:
  - projects/status
  verbs:
  - get
  - patch
  - update
---
{{- if .Values.rbac.allowProxyRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "jira-service-desk-operator.fullname" . }}-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
{{- end }}

---
{{- if .Values.rbac.allowMetricsReaderRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "jira-service-desk-operator.fullname" . }}-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
{{- end }}

{{- end }}
