{{- if not (.Capabilities.APIVersions.Has "jiraservicedesk.stakater.com/v1alpha1") -}}
    {{- fail "Required CRDs are missing, jira-service-desk-operator-crds chart is a pre-requisite of this chart" }}
{{ end }}

{{- if .Values.webhook.enabled -}}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "jira-service-desk-operator.fullname" . }}-serving-cert
  creationTimestamp: null
  name: {{ include "jira-service-desk-operator.fullname" . }}-mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "jira-service-desk-operator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-jiraservicedesk-stakater-com-v1alpha1-customer
  failurePolicy: Fail
  name: mcustomer.kb.io
  rules:
  - apiGroups:
    - jiraservicedesk.stakater.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - customers
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "jira-service-desk-operator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-jiraservicedesk-stakater-com-v1alpha1-project
  failurePolicy: Fail
  name: mproject.kb.io
  rules:
  - apiGroups:
    - jiraservicedesk.stakater.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - projects
{{- end -}}
