{{- if not (.Capabilities.APIVersions.Has "jiraservicedesk.stakater.com/v1alpha1") -}}
    {{- fail "Required CRDs are missing, jira-service-desk-operator-crds chart is a pre-requisite of this chart" }}
{{ end }}

{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jira-service-desk-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jira-service-desk-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
