{{- if not (.Capabilities.APIVersions.Has "jiraservicedesk.stakater.com/v1alpha1") -}}
    {{- fail "Required CRDs are missing, jira-service-desk-operator-crds chart is a pre-requisite of this chart" }}
{{ end }}

{{- if .Values.serviceMonitor.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: '{{ .Release.Name }}'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app: '{{ .Chart.Name }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
spec:
  selector:
    matchLabels:
      app: '{{ .Chart.Name }}'
      app.kubernetes.io/name: '{{ .Chart.Name }}'
      app.kubernetes.io/instance: '{{ .Release.Name }}'
  endpoints:
  - port: metrics
    path: /metrics
  namespaceSelector:
    matchNames:
    - '{{ .Release.Namespace }}'
{{- end }}