{{- if .Values.webhook.enabled -}}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "jira-service-desk-operator.fullname" . }}--serving-cert
  creationTimestamp: null
  name: {{ include "jira-service-desk-operator.fullname" . }}--validating-webhook-configuration
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: {{ include "jira-service-desk-operator.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-jiraservicedesk-stakater-com-v1alpha1-customer
    failurePolicy: Fail
    name: vcustomer.kb.io
    rules:
    - apiGroups:
      - jiraservicedesk.stakater.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - customers
  - clientConfig:
      caBundle: Cg==
      service:
        name: {{ include "jira-service-desk-operator.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-jiraservicedesk-stakater-com-v1alpha1-project
    failurePolicy: Fail
    name: vproject.kb.io
    rules:
    - apiGroups:
      - jiraservicedesk.stakater.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - projects
{{- end -}}


